{
 "title": "pFsense VPN",
 "description": "pfsense cluster VPN",
 "tags": [
  "vpn",
  "pfsense"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Current clients",
   "type": "stat",
   "description": "Current number of connected clients",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_server_connected_clients{instance=\"pfsense_openvpn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "table",
   "description": "List of active VPN users",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "openvpn_server_client_sent_bytes_total{instance=\"pfsense_openvpn\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Data recieved",
   "type": "timeseries",
   "description": "Data received by VPN clients",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "openvpn_server_client_received_bytes_total{instance=\"pfsense_openvpn\"}",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "timeseries",
   "description": "Data sent by VPN clients",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "openvpn_server_client_sent_bytes_total{instance=\"pfsense_openvpn\"}",
     "legendFormat": "{{common_name}}"
    }
   ]
  }
 ]
}